on: 
  pull_request:
  push:
    branches:
      - main

env:
  DEVELOPER_DIR: /Applications/Xcode_13.0.app/Contents/Developer

jobs:
  Test:
    runs-on: macos-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Test
      run: |
        swift package generate-xcodeproj 
        xcodebuild test -scheme AXSnapshot-Package -sdk iphonesimulator -destination "OS=15.0,name=iPhone 13 Mini"
